// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwF4ojqioEmNOdsPPngRYL8oU5PjIdLME',
    appId: '1:376668944323:web:08b72a8ef8c54ae63eaf76',
    messagingSenderId: '376668944323',
    projectId: 'flutter-chat-app-1cbcf',
    authDomain: 'flutter-chat-app-1cbcf.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1cbcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdpdZaKIkF_INIvBP5SPb9zNoDwDxCJ04',
    appId: '1:376668944323:android:bc469c29b5ccd19a3eaf76',
    messagingSenderId: '376668944323',
    projectId: 'flutter-chat-app-1cbcf',
    storageBucket: 'flutter-chat-app-1cbcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1xH6OzyRorYzv5zVf4WStxOoDw6VBvYY',
    appId: '1:376668944323:ios:4d2c0788153df3563eaf76',
    messagingSenderId: '376668944323',
    projectId: 'flutter-chat-app-1cbcf',
    storageBucket: 'flutter-chat-app-1cbcf.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1xH6OzyRorYzv5zVf4WStxOoDw6VBvYY',
    appId: '1:376668944323:ios:4d2c0788153df3563eaf76',
    messagingSenderId: '376668944323',
    projectId: 'flutter-chat-app-1cbcf',
    storageBucket: 'flutter-chat-app-1cbcf.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwF4ojqioEmNOdsPPngRYL8oU5PjIdLME',
    appId: '1:376668944323:web:4e14a85af956f2be3eaf76',
    messagingSenderId: '376668944323',
    projectId: 'flutter-chat-app-1cbcf',
    authDomain: 'flutter-chat-app-1cbcf.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1cbcf.firebasestorage.app',
  );

}